#! /bin/bash
if [ "$(ls -A dbs)" ]; then
        echo "Databases List"
        echo "--------------------"
        ls dbs
        echo "--------------------"
        ./mainMenu
else 
        echo "No Databases "
        echo "--------------------"
fi

